apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod01
  name: mypod01
spec:
  containers:
  - image: registry.k8s.io/busybox
    name: mypod01
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30 ; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

