apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod123
  name: pod123
spec:
  containers:
  - image: ubuntu
    name: pod123
    env:
      - name: firstname
        valueFrom: 
         configMapKeyRef:
           name: my-con-01
           key: firstname
    command: ['sh', '-c', 'echo hi', 'sleep 2600']
