apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: backend
  name: my-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: v1
    spec:
      containers:
      - image: nginx:1.23.4
        name: nginx
