apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod123
  name: mypod123
spec:
  containers:
  - image: registry.k8s.io/e2e-test-images/agnhost:2.40
    name: mypod123
    args:
      - liveness
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
