apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    env: demo
  name: my-replica-set
spec:
  replicas: 4
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
      - image: nginx:latest
        name: nginx
