apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod212
  name: mypod212
spec:
  containers:
  - image: registry.k8s.io/goproxy:0.1
    name: mypod212
    ports:
      - containerPort: 8080
    livenessProbe:
      tcpSocket:
         port: 3000
      initialDelaySeconds: 5
      periodSeconds: 5
